image: gitpod/workspace-full:2022-10-10-01-40-34

tasks:
  - name: Start
    init: |
      nix-shell --run 'bundle install'
    command: |
      nix-shell --run 'bundle exec jekyll serve --watch --drafts --source blog.mads-hartmann.com'

ports:
  - port: 4000
    onOpen: open-preview
