image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start
    init: |
      dagger project init
      dagger project update
    command: |
      dagger do watch

github:
  prebuilds:
    master: true
    branches: true

ports:
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - brody715.vscode-cuelang
