title: Mads Hartmann
description: Blog by Mads Hartmann
url: https://mads-hartmann.com

highlighter: rouge

collections:
  book_reviews:
    output: true

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

disqus:
  shortname: madshartmann

plugins:
  - jekyll-seo-tag

# Serving
detach: false
port: 4000
host: 0.0.0.0
baseurl: "" # does not include hostname
show_dir_listing: false
