name: Build & deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: "2.1.16"
          verbose: true
      - name: Install bundler
        run: gem install bundler
      - name: Setup bundler environment
        run: bundle install
      - name: Build site
        run: bundle exec jekyll build --source mads-hartmann.com
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync --region eu-central-1 _site/ s3://mads-hartmann.com/ --acl public-read --cache-control 'max-age=0,no-cache,no-store' --expires 'Thu, 01 Jan 1970 00:00:00 GMT'
      - name: Invalidate cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # if a region is not specified, the CLI will try to contact the local meta-data service
          # to determine the region.
          # cloudfront is global so we don't need to specify a region and we don't have the meta-data
          # service running as we're not in AWS, so we tell the CLI to not query the meta-data service.
          AWS_EC2_METADATA_DISABLED: true
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
