name: Build & deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Install bundler
        run: gem install bundler
      - name: Setup bundler environment
        run: bundle install
      - name: Build site
        run: bundle exec jekyll build
      - name: Deploy
        run: echo "Deploying"
